services:
  app1:
    image: my-app
    container_name: my-app-container-1
    expose:
      - "9090"
    volumes:
      - ~/app/config:/config
    restart: unless-stopped

  app2:
    image: my-app
    container_name: my-app-container-2
    expose:
      - "9090"
    volumes:
      - ~/app/config:/config
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    restart: unless-stopped